include: package:lints/recommended.yaml

# Uncomment the following section to specify additional rules.

linter:
  rules:
    - camel_case_types
    - prefer_single_quotes

analyzer:
  errors:
    prefer_single_quotes: warning