name: example
description: A sample command-line application.
version: 1.0.0
publish_to: 'none'
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.1.2

# Add regular dependencies here.
dependencies:
  flutter:
    sdk: flutter
  # path: ^1.8.0
  convert: ^3.1.1
  veil_light_plugin:
    # When depending on this package from a real application you should use:
    #   veil_light_plugin: ^x.y.z
    # See https://dart.dev/tools/pub/dependencies#version-constraints
    # The example app is bundled with the plugin so we use a path dependency on
    # the parent directory to use the current plugin's version.
    path: ../
  bip32: ^2.0.0

dev_dependencies:
  lints: ^6.0.0
  test: 1.26.2
