name: veil_light_plugin
description: Veil light plugin project.
version: 0.0.1
homepage:

environment:
  sdk: '>=3.1.2 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  convert: ^3.1.1
  flutter_bitcoin: ^1.0.1
  http: ^1.1.2
  json_annotation: ^4.8.0
  pointycastle: ^3.7.4
  ffi: ^2.1.2
  plugin_platform_interface: ^2.1.8
  bip32: ^2.0.0
  bip39: ^1.0.6
  bech32: ^0.2.2
  bs58check: ^1.0.2
  dart_varuint_bitcoin: ^1.0.3

dev_dependencies:
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  lints: ^4.0.0
  test: 1.25.2
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        ffiPlugin: true
      ios:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      windows:
        ffiPlugin: true